spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kiosk?characterEncoding=UTF-8
    username: root
    password: mariadb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG
